### PR TITLE
Update chinese README

### PR DESCRIPTION
**Pull request by yingyi666**
i have use the latest version test, it work ok ,and solved all my previous questions.
thanks

### CODE REVIEW

**Comment by yingyi666** [comment]
And this is a great project, especially for embedded databases. I found it on awesome-go, and I'm looking forward to its later version.

**Comment by yingyi666** [comment]
ok，I will follow up on this project.😁

**Comment by ASWLaunchs** [comment]
> i have use the latest version test, it work ok ,and solved all my previous questions. thanks

I am sorry for the translated mistake .

**Comment by ASWLaunchs** [comment]
> Thank you for your contribution, @yingyi666! If you like clover, you are welcome to join our gitter channel to share ideas about possible improvements. Since I don't understand chinese, I'll ask @ASWLaunchs (who is the author of the chinese version of the README) to give a look at this before merging :=)

Tonight I will review it and submit it. I'm really sorry for this translation mistake

**Comment by ASWLaunchs** [comment]
> Thank you for your contribution, @yingyi666! If you like clover, you are welcome to join our gitter channel to share ideas about possible improvements. Since I don't understand chinese, I'll ask @ASWLaunchs (who is the author of the chinese version of the README) to give a look at this before merging :=)

I have just noticed that he(yingyi666) has submitted pr and his Chinese translation is correct.

**Pull request merged**
