### PR TITLE
Chinese document synchronization

### PR DESCRIPTION
**Pull request by yingyi666**
I updated the Chinese documents according to readme, but I found that some descriptions in the English documents did not seem to be correct.

for example :
Invalid types leaves the document untouched:

```go
doc := c.NewDocument()
doc.Set("myField", make(chan struct{}))

log.Println(doc.Has("myField")) // will output false
```

The code above is printed out as true after I run it.

This is the complete code.

```go
package main

import (
	"log"

	c "github.com/ostafen/clover"
)

func main() {
	db, _ := c.Open("clover-db")
	defer db.Close()

	doc := c.NewDocument()
	doc.Set("myField", make(chan struct{}))

	log.Println(doc.Has("myField"))
}
```

and when i want to insert the  document to collection, it panic

```bash
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/ostafen/clover.(*DB).InsertOne(0xc00063ff58?, {0x1492124?, 0xc000258b70?}, 0xc000217f40)
        C:/Users/jin/go/pkg/mod/github.com/ostafen/clover@v1.1.0/db.go:91 +0xa5
main.main()
        D:/project/go/test/main.go:17 +0x185
exit status 2
```

And with regard to pointers, it completely adopts value copying and cancels automatic references, right?

My English is not good. There may be some mistakes in my understanding.

### CODE REVIEW

**Comment by ostafen** [comment]
Which version of the library are you using?

**Comment by yingyi666** [comment]
> Which version of the library are you using? If you downloaded the library using go modules, then you probably got v1.1.0 version, which is not aligned with last changes on data types internal

That's no problem. I do use go modules, and then how do I get the latest version?

**Comment by yingyi666** [comment]
ok, thanks

**Comment by ostafen** [comment]
Why did you close the PR?

**Comment by yingyi666** [comment]
> Why did you close the PR?
I am going to re-launch a new pr after installing the latest version test

**Pull request closed without merging**
