### PR TITLE
Adds Marshal for API symmetry

### PR DESCRIPTION
**Pull request by xxxserxxx**
This balances the `Unmarshal` with a `Marshal` function.

### CODE REVIEW

**Comment by ostafen** [comment]
Hi, xxxserxxx! Thank you for contributing.

Some things: for consistency with the json.Marshal api, you should return a pair (*Document, error).
I also noticed that you have created a new file "document_test.go". That is a good idea, but we this implies moving all the test referring to document in that file. What do you say of making a separate PR for that?
That is to say, insert the new test in the db_test.go file for this PR and in a separate PR, move all the document tests to a new document_test file.
Thank you again!

**Comment by xxxserxxx** [comment]
Yes, returning error is better than what this does. I'll update the patch.

I honestly didn't notice `db_test.go`; I'll move the test there. The file naming is just the pattern I use -- I don't believe it's necessary.

Sorry about the flubs. I'd written out a feature request and realized I'd spent more time than if I just did a PR, so I kind of threw it together and sent it to you. I didn't think about it as much as I probably should have.

**Comment by ostafen** [comment]
Hi, thank you for the correction. Some more things.

```
if json.Unmarshal(bs, &kvs) != nil {
return nil, err
}
```

In the previous code, you are not correctly catching the error returned by function json.Unmarshal at line 105, you are simply returning the error previously defined at line 100 (the one returned by json.Marshal), which at that point of the execution will always be nil.

Please, replace lines 105-108 with this:

```
err = json.Unmarshal(bs, &kvs)
return NewDocumentOf(kvs), err
```
There is no need to check if err != nil, since we immediately return it to the user. This way we improve readability of code.

Regarding tests, you should use the require library for making assertions.
Every error returned by a function should be followed by a require.NoError(t, err) call.
So, this snippet: 

``go
d, err := c.Marshal(expected)
if err != nil {
    t.Errorf("did not expect an error marshaling here")
}
d.Unmarshal(&got)
``
becomes: 

``go
d, err := c.Marshal(expected)
require.NoError(t, err)
err = d.Unmarshal(&got)
require.NoError(t, err)
``

while every check as:

**Comment by ostafen** [comment]
Why did you close the PR?

**Comment by xxxserxxx** [comment]
I won't be using clover any longer, and I didn't have a chance to make the final changes before I made my decision so the PR would have remained incomplete. I didn't want to leave you hanging waiting for me to fix the code.

**Comment by ostafen** [comment]
I''ll patch the code myself, since it is a minor change. Thanks anyway for the interest.

**Pull request closed without merging**
